import { AUTHENTICATED_PARAM, AUTHENTICATED_PATH, AUTHENTICATED_PROPS } from "./authenticatedType";
import { NOT_AUTHENTICATED_PARAM, NOT_AUTHENTICATED_PATH, NOT_AUTHENTICATED_PROPS } from "./notAuthenticatedType";

export {
  NOT_AUTHENTICATED_PARAM,
  NOT_AUTHENTICATED_PATH,
  NOT_AUTHENTICATED_PROPS,
  AUTHENTICATED_PARAM,
  AUTHENTICATED_PATH,
  AUTHENTICATED_PROPS,
}